
ccflags-y := -Iarch/$(SRCARCH)/xenomai/include -Iinclude/xenomai \
	-Idrivers/xenomai/analogy

obj-$(CONFIG_XENO_DRIVERS_ANALOGY_S526) += analogy_s526.o
obj-$(CONFIG_XENO_DRIVERS_ANALOGY_S626) += analogy_s626.o

analogy_s526-y := s526.o 
analogy_s626-y := s626.o
